on: [push]

jobs:
  run-bugbug-tests:
    runs-on: ubuntu-latest
    name: Run BugBug Tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run BugBug Cloud Runner
        id: run-bugbug-tests
        uses: bugbug-io/bugbug-github-action@v1.2.1
        with:
          apiToken: "69440165985146e828a7b195404be2b10b0b273d"
          testId: "276dc705-f1a7-4758-b8d0-6ff8038bbeca"
          
      - name: Getting Run Output
        run: |
          echo "Suite Run ID: ${{ steps.run-bugbug-tests.outputs.suiteRunId }}"
          echo "Test Run ID: ${{ steps.run-bugbug-tests.outputs.testRunId }}"
