name: Run BugBug Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  repository_dispatch:
    types: [bugbug-test-completed]

jobs:
  run-bugbug-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: BugBug Cloud Runner
        uses: bugbug-io/bugbug-github-action@v1.2.1
        with:
          apiToken: '69440165985146e828a7b195404be2b10b0b273d'
          testId: '276dc705-f1a7-4758-b8d0-6ff8038bbeca'

  handle-bugbug-webhook:
    runs-on: ubuntu-latest
    needs: run-bugbug-tests

    steps:
      - name: Check test results from BugBug
        run: |
          response=$(curl -X GET "https://api.bugbug.io/v1/tests/results/$TEST_RUN_ID" \
            -H "Authorization: Bearer ${{ secrets.BUGBUG_API_TOKEN }}")
          status=$(echo "$response" | jq -r '.status')
          echo "Received status: $status"
          if [[ "$status" == "passed" ]]; then
            echo "Tests passed!"
            exit 0
          elif [[ "$status" == "failed" ]]; then
            echo "Tests failed!"
            exit 1
          fi
