name: Run BugBug Tests and Send Data
continue-on-error: true  # Permette al workflow di continuare anche se fallisce
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-bugbug-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Recupera info PR o Push
      - name: Get PR/Push Info
        id: pr_info
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "PR_TITLE=$(jq -r .pull_request.title $GITHUB_EVENT_PATH)" >> $GITHUB_ENV
            echo "PR_NUMBER=$(jq -r .pull_request.number $GITHUB_EVENT_PATH)" >> $GITHUB_ENV
            echo "PR_AUTHOR=$(jq -r .pull_request.user.login $GITHUB_EVENT_PATH)" >> $GITHUB_ENV
            echo "PR_URL=$(jq -r .pull_request.html_url $GITHUB_EVENT_PATH)" >> $GITHUB_ENV
            echo "EVENT_TYPE=pull_request" >> $GITHUB_ENV
          else
            echo "COMMIT_MESSAGE=$(git log -1 --pretty=%B)" >> $GITHUB_ENV
            echo "COMMIT_AUTHOR=$(git log -1 --pretty=%an)" >> $GITHUB_ENV
            echo "COMMIT_SHA=$(git rev-parse HEAD)" >> $GITHUB_ENV
            echo "EVENT_TYPE=push" >> $GITHUB_ENV
          fi

      # Esegue BugBug test e salva gli ID di esecuzione
      - name: Run BugBug Tests
        id: bugbug_test
        uses: bugbug-io/bugbug-github-action@v1.2.1
        with:
          apiToken: '69440165985146e828a7b195404be2b10b0b273d'
          suiteId: '72e6a1df-0e04-4c32-8db5-d10a39542352'
          debug: 'true'
        

      # Invio dati a un endpoint
      - name: Send Data to Webhook
        run: |
          curl -X POST "https://hook.eu1.make.com/i46n7r41xhkxw1wz4uikk6vevrsvbfev" \
          -H "Content-Type: application/json" \
          -d '{
            "event_type": "${{ env.EVENT_TYPE }}",
            "pr_title": "${{ env.PR_TITLE }}",
            "pr_number": "${{ env.PR_NUMBER }}",
            "pr_author": "${{ env.PR_AUTHOR }}",
            "pr_url": "${{ env.PR_URL }}",
            "commit_message": "${{ env.COMMIT_MESSAGE }}",
            "commit_author": "${{ env.COMMIT_AUTHOR }}",
            "commit_sha": "${{ env.COMMIT_SHA }}",
            "bugbug_suite_run_id": "${{ steps.bugbug_test.outputs.suiteRunId }}",
            "bugbug_test_run_id": "${{ steps.bugbug_test.outputs.testRunId }}"
          }'
