

 name: Run BugBug Tests

 on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  

 jobs:
  run-bugbug-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: BugBug Cloud Runner
        uses: bugbug-io/bugbug-github-action@v1.2.1
        with:
          apiToken: '69440165985146e828a7b195404be2b10b0b273d'
          suiteId: '72e6a1df-0e04-4c32-8db5-d10a39542352'
          debug: 'true'
          variables: 'prtitle=ciaoooo'
          
        
        
