

 name: Run BugBug Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  run-bugbug-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: BugBug Cloud Runner
        uses: bugbug-io/bugbug-github-action@v1.2.1
        with:
          apiToken: '69440165985146e828a7b195404be2b10b0b273d'
          testId: '276dc705-f1a7-4758-b8d0-6ff8038bbeca'
